version: '3.7'

services:

  cassandra-0:
    container_name: cassandra-0
    hostname: cassandra-0
    image: cassandra:latest
    environment: &environment
      CASSANDRA_SEEDS: 'cassandra-0,cassandra-1'
      CASSANDRA_CLUSTER_NAME: 'Otus-hw'

  cassandra-1:
    container_name: cassandra-1
    hostname: cassandra-1
    image: cassandra:latest
    environment: *environment

  cassandra-2:
    container_name: cassandra-2
    hostname: cassandra-2
    image: cassandra:latest
    environment: *environment